In [2]:
import scipy.io
from scipy.io import loadmat
import numpy as np

In [30]:
# file_name = f'VGG_L2_Weights_savmat\W_VGG_{0}_L2.mat'  # Construct the file name
data = loadmat('VGG_L2_Weights_savmat\W_VGG_0_L2.mat')   # Load the .mat file
print(data.keys())                                       # Print the keys of the dictionary
data_array = np.array(data['W_VGG_0_L2'])            # Convert the dictionary to an array
print(data_array)

dict_keys(['__header__', '__version__', '__globals__', 'W_VGG_0_L2'])
[[[-0.08479716  0.04702415  0.02738129]
  [ 0.06896675 -0.01071115  0.01893378]
  [-0.09657004  0.04051069 -0.02284791]]

 [[ 0.0425146   0.00061433  0.03473117]
  [-0.00882157  0.03499418  0.00075186]
  [-0.08737816 -0.03976802  0.05229968]]

 [[-0.02219826 -0.08177157 -0.10348193]
  [ 0.07388628  0.05317178 -0.06569532]
  [ 0.05510584 -0.01636489  0.08632845]]

 [[-0.05874295  0.08944963  0.00334193]
  [ 0.06665146  0.04167455 -0.03992347]
  [-0.05818787  0.09428585  0.06674519]]

 [[-0.0071882   0.03277771  0.08060864]
  [ 0.06320775  0.06346922 -0.09923088]
  [-0.04613015 -0.09382337  0.02979604]]

 [[-0.04351232 -0.01386665  0.07992035]
  [ 0.09338699  0.01638138  0.05743853]
  [-0.02756297 -0.02119384  0.09172048]]

 [[ 0.08487563 -0.04106275 -0.00993741]
  [-0.08857425  0.05908768  0.08789975]
  [ 0.06021561  0.07719421  0.01838367]]

 [[-0.04922322  0.01511865 -0.04585883]
  [ 0.07371259 -0.0714414   0.041635

In [42]:
x = []
data_list = []
for i in range(0, 16):
    # file_name = f'VGG_L2_Weights_savmat\W_VGG_{i}_L2.mat'  # Construct the file name
    data = loadmat(f'VGG_L2_Weights_savmat\W_VGG_{i}_L2.mat')   # Load the .mat file
    data_array = np.array(data[f'W_VGG_{i}_L2'])            # Convert the dictionary to an array
    data_list.append(data_array)
x = data_list[0].reshape(-1)
print(x)

[-0.08479716  0.04702415  0.02738129  0.06896675 -0.01071115  0.01893378
 -0.09657004  0.04051069 -0.02284791  0.0425146   0.00061433  0.03473117
 -0.00882157  0.03499418  0.00075186 -0.08737816 -0.03976802  0.05229968
 -0.02219826 -0.08177157 -0.10348193  0.07388628  0.05317178 -0.06569532
  0.05510584 -0.01636489  0.08632845 -0.05874295  0.08944963  0.00334193
  0.06665146  0.04167455 -0.03992347 -0.05818787  0.09428585  0.06674519
 -0.0071882   0.03277771  0.08060864  0.06320775  0.06346922 -0.09923088
 -0.04613015 -0.09382337  0.02979604 -0.04351232 -0.01386665  0.07992035
  0.09338699  0.01638138  0.05743853 -0.02756297 -0.02119384  0.09172048
  0.08487563 -0.04106275 -0.00993741 -0.08857425  0.05908768  0.08789975
  0.06021561  0.07719421  0.01838367 -0.04922322  0.01511865 -0.04585883
  0.07371259 -0.0714414   0.04163508  0.08401862  0.09180918  0.00602304
 -0.00450823  0.0134948   0.05139038  0.00061166  0.02258686 -0.02584096
  0.09175963  0.06559967  0.00184221  0.05751286  0

In [50]:
from binary_fractions import TwosComplement
data_list = []

# Iterate through the file names
for i in range(17):  # Assuming you want to load W0_L1.mat, W1_L1.mat, and W2_L1.mat
    file_name = f'VGG_L2_Weights_savmat\W_VGG_{i}_L2.mat'  # Construct the file name
    data = loadmat(file_name)   # Load the .mat file

    # Convert the data to a NumPy array
    data_array = np.array(data[f'W_VGG_{i}_L2'])  # Replace 'variable_name' with the actual variable name in the .mat file

    data_list.append(data_array)  # Append the NumPy array to the list
print(data_list[0][0])

[[-0.08479716  0.04702415  0.02738129]
 [ 0.06896675 -0.01071115  0.01893378]
 [-0.09657004  0.04051069 -0.02284791]]


In [51]:
# Now data_list contains the data from all three .mat files as NumPy arrays
# You can access each data array using indexing
# For example, to access data from W1_L1.mat as a NumPy array:
for i in range (0,17):
    data_from_W1_L1 = data_list[i][i]
    data_from_W2_L1 = data_list[i+1][i]
    f = open(f"VGG_W{i}_L2.txt",'w')
    # print(data_from_W1_L1)
    data_from_W1_L1 = data_from_W1_L1.reshape(-1)
    data_from_W2_L1 = data_from_W2_L1.reshape(-1)

    # print(data_from_W1_L1)
    Str_Data1 = ["%.8f" % x for x in data_from_W1_L1]
    Str_Data2 = ["%.8f" % x for x in data_from_W2_L1]

    # print(Str_Data1)
    # print(Str_Data2)
    # # print(Str_Data)
    x1 = [float(items) for items in Str_Data1]
    x11 = [float(items) for items in Str_Data2]

    # print(x1)
    x2 = []
    x22 = []

    for items in x1:
        x2.append(TwosComplement(items))
    # print(x2)
    for items in x11:
        x22.append(TwosComplement(items))

    x12 = []
    for i in range (0,len(x2)):
        x12.append(f'{x2[i][0]}{x2[i]}')

    x112 = []
    for i in range (0,len(x22)):
        x112.append(f'{x2[i][0]}{x22[i]}')

    # print(x112)
    x14 = []
    x114 = []

    x13 = []
    x113 = []

    for items in x12:
        x13.append (items.replace (".",""))
    # print(x13)

    for items in x112:
        x113.append (items.replace (".",""))
    # print(x113)

    for items in x13:
        x14.append(items[0:16])
    # print(x14)

    for items in x113:
        x114.append(items[0:16])
    # print(x114)

    x_final = np.concatenate((x14,x114), axis=0)
    x_final = x_final[: len(x_final) - 2]
    # print(x_final)

    for items in x_final:
        print(items,file = f)
    f.close()

IndexError: list index out of range