In [1]:
import numpy as np
from scipy.io import loadmat


In [19]:
x = []
data_list = []
for i in range (0,16):
    data = loadmat(f'W{i}_L2.mat')
    data_array = np.array(data[f'W{i}_L2'])
    data_list.append(data_array)
x = data_list[0].reshape(-1)
print(x.shape)

NameError: name 'data_list' is not defined

In [11]:
# print(f.keys())
f1 = f['W0_L2']
print(f1.shape)

(6, 5, 5)


In [18]:
print(f1[1])
print(f1[1][0][0])

[[ 0.05395135 -0.05001511  0.01657931 -0.07245898 -0.02574239]
 [ 0.03104182  0.04049673 -0.0347704   0.03138778 -0.0181501 ]
 [ 0.01666885  0.08707914  0.09922986 -0.04434356  0.04332601]
 [ 0.07949588  0.02216134  0.04939079  0.11875132  0.13360672]
 [ 0.04735415 -0.06454994  0.03659964 -0.02437836 -0.09229976]]
0.05395135


In [16]:
from binary_fractions import TwosComplement
x = TwosComplement(float(f1[0][0][0]))
print(x)

0.00010001101000111011100011
