In [40]:
from scipy.io import loadmat
import glob
import os
import numpy as np
from binary_fractions import TwosComplement

In [28]:
files_list = sorted(glob.glob('*.mat'), key=os.path.getmtime)

In [29]:
# files_list = glob.glob('*.mat')
# print(len(files_list))
# files_list = sorted(files_list)
print(files_list[479])

output_fm_pool_479.mat


In [70]:
x = []
data_list = []
for i in range (0, 480):
    data = loadmat(f'output_fm_pool_{i}.mat')
    data_array = np.array(data[f'output_fm_pool_{i}'])
    data_list.append(data_array)
    x1 = data_list[i].reshape(-1)
    x.append(x1)
print(len(x[0]))


196


In [38]:
# for files in files_list:
    # print(str(files))
data_list = []
for i in range (len(files_list)):
    data = loadmat(str(files_list[i]))
    data_list.append(data)
print(data.keys())
print(len(data_list))
print(data_list[0].keys())

dict_keys(['__header__', '__version__', '__globals__', 'output_fm_pool_479'])
480
dict_keys(['__header__', '__version__', '__globals__', 'output_fm_pool_0'])


In [35]:
print(data_list)

[{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Tue Oct 17 12:49:17 2023', '__version__': '1.0', '__globals__': [], 'output_fm_pool_0': array([[ 32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,
         32],
       [ 32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,
         32],
       [ 32,  32,  42,  34,  32,  32,  32,  32,  32,  32,  32,  32,  32,
         32],
       [ 32,  32,  43,  18,  16,   4,   0,   3,   3,   1,   6,  29,  32,
         32],
       [ 32,  32,  93, 200, 225, 203, 181, 173, 183, 175,  84,  57,  32,
         32],
       [ 32,  32,  86, 159, 183, 215, 233, 241, 255, 214, 148,  88,  32,
         32],
       [ 32,  32,  32,  32,  33,  41,  50,  67,  63, 157, 157,  62,  32,
         32],
       [ 32,  32,  32,  32,  32,  32,  38,  54, 128, 171, 130,  35,  32,
         32],
       [ 32,  32,  32,  32,  32,  33,  43,  56, 146, 158,  54,  32,  32,
         32],
       [ 32,  32,  32,  32,  32,  42,  41, 129, 168, 115,  32,  3

In [26]:
print(data_list[0].keys())
temp =data_list[479]['output_fm_pool_79_5'] 
# print(data_list['output_fm_pool_0_0'])
print(temp)

dict_keys(['__header__', '__version__', '__globals__', 'output_fm_pool_0_0'])
[[ 37  37  37  37  37  37  37  37  37  37  37  37  37  37]
 [ 37  37  37  37  37  37  37  37  37  37  37  37  37  37]
 [ 37  37  37  37  37  38  44  39  37  37  37  37  37  37]
 [ 37  38  45  42  36  14   8   0  15  19  12  23  37  37]
 [ 37  40  45  37  85 112 138 183 200 195 153  84  43  37]
 [ 37  39 120 216 235 239 245 255 239 202 166  98  44  37]
 [ 37  45 122 218 233 232 226 214 166 181 174 101  37  37]
 [ 37  37  52  77  79  72  64  97 177 201 170  85  37  37]
 [ 37  37  37  37  46  44  91 177 207 211 129  40  37  37]
 [ 37  37  37  46  46  73 167 210 201 140  47  37  37  37]
 [ 37  37  43  46  71 166 197 204 150  49  37  37  37  37]
 [ 37  37  37 116 185 189 187 145  51  37  37  37  37  37]
 [ 37  37  52 141 211 226 163  79  37  37  37  37  37  37]
 [ 37  37  43 100 199 219 141  42  37  37  37  37  37  37]]


In [ ]:
for i in range (len(data_list)):
    for j in range (0, 80):
        
for i in range (0, 80):
    for j in range (0, 6):
        

In [ ]:
for i in range (0,10):
    filename = open(f'file_{i}.txt', 'w')
    for j in range (0, 8):
        for k in range (0, 6):
            data = loadmat(f'output_fm_pool{i+j}_{k}.mat')
            